name: API

on:
  push:
    paths:
      - ".github/workflows/api*"
      - "projects/api/**/*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.x"

      - name: Set up dependencies
        run: |
          cd projects/api/
          pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Run linters
        run: |
          cd projects/api/
          task lint

  tests:
    name: Tests
    runs-on: ubuntu-latest
    container: python:3.11-slim
    env:
      INFISICAL_ADDRESS: ${{ secrets.INFISICAL_ADDRESS }}
      INFISICAL_TOKEN: ${{ secrets.INFISICAL_TOKEN }}
      TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
      TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      TEST_TOKEN_URL: ${{ secrets.TEST_TOKEN_URL }}
      TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          cd projects/api/
          pip install -U pip poetry
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Set up database
        run: |
          cd projects/api/
          aerich init-db || true
          aerich upgrade || true

      - name: Run tests
        run: |
          cd projects/api/
          task test

  deploy:
    name: Build and Deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
    needs: [lint, tests]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      DOCKERHUB_REPOSITORY: vision-ai
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: prefeiturario
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCR_SERVICE: ${{ secrets.GCR_SERVICE }}
      GCR_REGION: ${{ secrets.GCR_REGION }}
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Copy libs to API directory
        run: |
          mkdir -p projects/api/libs
          cp -r projects/libs/* projects/api/libs/

      - name: Docker Auth
        id: docker-auth
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./projects/api
          file: ./projects/api/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.revision=${{ github.sha }}
          build-args: |
            BUILDKIT_INLINE_CACHE=1

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ env.GCP_SA_KEY }}'

      - name: Deploy to Google Cloud Run (Production)
        if: github.ref == 'refs/heads/main'
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.GCR_SERVICE }}-production
          region: ${{ env.GCR_REGION }}
          image: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
          flags: '--add-cloudsql-instances=datario:us-central1:postgres-side --port=80 --allow-unauthenticated --concurrency=100'
          secrets: |
            ENVIRONMENT=VISION_AI_API_PROD_ENVIRONMENT:latest
            INFISICAL_ADDRESS=VISION_AI_API_PROD_INFISICAL_ADDRESS:latest
            INFISICAL_TOKEN=VISION_AI_API_PROD_INFISICAL_TOKEN:latest

      - name: Deploy to Google Cloud Run (Staging)
        if: github.ref == 'refs/heads/development'
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.GCR_SERVICE }}-staging
          region: ${{ env.GCR_REGION }}
          image: docker.io/${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:${{ github.sha }}
          flags: '--add-cloudsql-instances=datario:us-central1:postgres-side --port=80 --allow-unauthenticated --concurrency=10'
          secrets: |
            ENVIRONMENT=VISION_AI_API_STAGING_ENVIRONMENT:latest
            INFISICAL_ADDRESS=VISION_AI_API_STAGING_INFISICAL_ADDRESS:latest
            INFISICAL_TOKEN=VISION_AI_API_STAGING_INFISICAL_TOKEN:latest
